---

- hosts: all
  remote_user: vagrant
  tasks:
  - name: Actualizacion
    command: sudo apt-get update
  - name: Instalar Python
    command: sudo apt-get -y install python python3
  - name: Instalar Pip
    command: sudo apt-get -y install python-pip python3-pip
  - name: Actualizar Pip
    command: pip3 install --upgrade pip
  - name: Instalar Git
    command: sudo apt-get -y install git
